# Generated by Django 4.2 on 2023-06-07 12:18

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RepBenchWeb', '0012_alter_dataset_additional_info_alter_dataset_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injectedcontainer',
            name='info',
        ),
        migrations.AddField(
            model_name='injectedcontainer',
            name='additional_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='injectedcontainer',
            name='features',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='injectedcontainer',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='injectedcontainer',
            name='ts_nbr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='ts_nbr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='injectedcontainer',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='injectedcontainer',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
